### ISSUE TITLE
CentOS support

### ISSUE THREAD

**Issue by ghost** [frekele/docker-gradle#114]
Hello @frekele!

Thanks for the awesome work! Your Gradle images helped me a lot. They appeared just in time. 👍

I suppose you have some kind of automation in background, so I would like to ask one think. Your images are currently based on Debian Linux. Do you plan to create CentOS-based Gradle images?

Many thanks again. Well done!

**Comment by frekele** [comment]
@RomanSyroeshko , at the moment I have no plans.

Maybe next year I will think about it. 😃
